// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _1013.Models;

public partial class Budget
{
    public int id { get; set; }

    public string account { get; set; }

    public int amount { get; set; }

    public DateTime startdate { get; set; }

    public DateTime enddate { get; set; }
}