// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _1013.Models;

public partial class expenses
{
    public int id { get; set; }

    public string account { get; set; }

    public DateTime date { get; set; }

    public int amount { get; set; }

    public string category { get; set; }

    public string note { get; set; }
}