// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _1013.Models;

public partial class Invoice
{
    public int Id { get; set; }

    public string VehicleNumber { get; set; }

    public DateTime InvoiceDate { get; set; }

    public decimal Amount { get; set; }

    public string InvoiceNumber { get; set; }

    public string Category { get; set; }
}