// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _1013.Models;

public partial class member
{
    public string account { get; set; }

    public string password { get; set; }

    public string salt { get; set; }

    public string name { get; set; }

    public string phone { get; set; }

    public string mail { get; set; }

    public string VehicleNumber { get; set; }

    public int? RecurringExpenseId { get; set; }

    public string ResetPasswordToken { get; set; }

    public DateTime? TokenExpiration { get; set; }
}