// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _1013.Models;

public partial class RecurringExpense
{
    public int Id { get; set; }

    public string account { get; set; }

    public string Category { get; set; }

    public int Amount { get; set; }

    public string Note { get; set; }

    public string FrequencyType { get; set; }

    public string DayOfWeek { get; set; }

    public int DayOfMonth { get; set; }

    public int RepeatCount { get; set; }

    public DateTime StartDate { get; set; }
}