// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _1013.Models;

public partial class UserSelectedInvoice
{
    public int Id { get; set; }

    public string account { get; set; }

    public string InvoiceNumber { get; set; }
}